-- Due to message size limits, this file contains the table schema.
WITH CTE AS(
SELECT DEPARTMENT
FROM EMPLOYEES
GROUP BY DEPARTMENT HAVING 
SUM(CASE WHEN GENDER = 'M' THEN SALARY ELSE 0 END) <
SUM(CASE WHEN GENDER = 'F' THEN SALARY ELSE 0 END)
)
SELECT C.DEPARTMENT, E.GENDER, SUM(E.SALARY) AS TOTAL_SALARY
FROM EMPLOYEES E JOIN CTE C ON E.DEPARTMENT = C.DEPARTMENT
GROUP BY C.DEPARTMENT, E.GENDER ORDER BY  C.DEPARTMENT
